"""
backend/models/temporal_model.py
═══════════════════════════════════════════════════════════════
FocusForge v2 — ML Model Layer

LSTM-based cognitive state predictor.
Pure NumPy — zero extra ML-framework dependencies (no PyTorch / TensorFlow).

Architecture
────────────
  Input   →  rolling window of 30 feature vectors  (SEQUENCE_LEN × FEATURE_DIM)
  LSTM    →  64 hidden units  (captures temporal dynamics)
  Head    →  switch_prob  |  proc_score  |  cog_state_logits × 5

Training strategy (weak supervision)
─────────────────────────────────────
  Ground truth is approximated with pseudo-labels generated by
  WeakLabelGenerator (feature_logger.py).  No manual annotation needed.
  This is a standard research technique used in behaviour analysis.

Confidence scores
─────────────────
  switch_confidence  — how far switch_prob is from 0.5 (0=uncertain, 1=definite)
  state_confidence   — 1 - normalised entropy of cognitive-state distribution
"""

import numpy as np
import json
import time
import logging
import os
from collections import deque
from dataclasses import dataclass, field
from typing import Dict, Optional, Tuple

logger = logging.getLogger("temporal_model")

# ── Architecture constants ────────────────────────────────────────────────────
FEATURE_DIM    = 12
SEQUENCE_LEN   = 30      # ~1 second of frames at 30 fps
HIDDEN_SIZE    = 64
NUM_COG_STATES = 5

COG_STATE_IDX = {
    "focused": 0, "confused": 1, "high_load": 2,
    "fatigued": 3, "distracted": 4,
}
IDX_COG_STATE = {v: k for k, v in COG_STATE_IDX.items()}


# ── Pure-NumPy LSTM cell ──────────────────────────────────────────────────────

class NumpyLSTMCell:
    """Standard LSTM cell: forget / input / gate / output gates."""

    def __init__(self, input_size: int, hidden_size: int, seed: int = 42):
        rng   = np.random.default_rng(seed)
        scale = np.sqrt(2.0 / (input_size + hidden_size))
        concat = input_size + hidden_size

        def W(r): return rng.normal(0, scale, (r, concat)).astype(np.float32)
        def b(r): return np.zeros(r, dtype=np.float32)

        self.Wf, self.bf = W(hidden_size), b(hidden_size)
        self.Wi, self.bi = W(hidden_size), b(hidden_size)
        self.Wg, self.bg = W(hidden_size), b(hidden_size)
        self.Wo, self.bo = W(hidden_size), b(hidden_size)

    @staticmethod
    def _sig(x):  return 1.0 / (1.0 + np.exp(-np.clip(x, -15, 15)))

    def forward(self, x: np.ndarray, h: np.ndarray, c: np.ndarray):
        xh = np.concatenate([x, h])
        f  = self._sig(self.Wf @ xh + self.bf)
        i  = self._sig(self.Wi @ xh + self.bi)
        g  = np.tanh  (self.Wg @ xh + self.bg)
        o  = self._sig(self.Wo @ xh + self.bo)
        c2 = f * c + i * g
        h2 = o * np.tanh(c2)
        return h2, c2

    def load_weights(self, w: dict):
        for k in ("Wf","bf","Wi","bi","Wg","bg","Wo","bo"):
            if k in w:
                setattr(self, k, np.array(w[k], dtype=np.float32))


class NumpyLSTMHead:
    """Linear projection: hidden → [switch_prob, proc_score, cog_logits×5]"""

    def __init__(self, hidden_size: int, num_states: int, seed: int = 99):
        rng   = np.random.default_rng(seed)
        scale = np.sqrt(2.0 / hidden_size)
        self.W = rng.normal(0, scale, (2 + num_states, hidden_size)).astype(np.float32)
        self.b = np.zeros(2 + num_states, dtype=np.float32)

    @staticmethod
    def _sig(x):     return 1.0 / (1.0 + np.exp(-np.clip(x, -15, 15)))
    @staticmethod
    def _softmax(x):
        e = np.exp(x - x.max()); return e / e.sum()

    def forward(self, h: np.ndarray) -> Tuple[float, float, np.ndarray]:
        out = self.W @ h + self.b
        return float(self._sig(out[0])), float(self._sig(out[1])), self._softmax(out[2:])

    def load_weights(self, w: dict):
        if "W" in w: self.W = np.array(w["W"], dtype=np.float32)
        if "b" in w: self.b = np.array(w["b"], dtype=np.float32)


# ── Feature vector (pipeline → model bridge) ─────────────────────────────────

@dataclass
class ModelFeatureVector:
    """Normalised [0-1] feature vector fed to the LSTM."""
    head_yaw_dev:     float = 0.0
    gaze_instability: float = 0.0
    ear_normalised:   float = 0.5
    blink_rate_norm:  float = 0.5
    brow_furrow:      float = 0.0
    forward_lean:     float = 0.0
    body_stability:   float = 1.0
    hand_speed:       float = 0.0
    focus_score:      float = 0.5
    cognitive_load:   float = 0.3
    fatigue_score:    float = 0.0
    procrastin_score: float = 0.0

    def to_array(self) -> np.ndarray:
        return np.array([
            self.head_yaw_dev, self.gaze_instability, self.ear_normalised,
            self.blink_rate_norm, self.brow_furrow, self.forward_lean,
            self.body_stability, self.hand_speed, self.focus_score,
            self.cognitive_load, self.fatigue_score, self.procrastin_score,
        ], dtype=np.float32)

    def to_dict(self) -> dict:
        return {
            "head_yaw_dev": self.head_yaw_dev,
            "gaze_instability": self.gaze_instability,
            "ear_normalised": self.ear_normalised,
            "blink_rate_norm": self.blink_rate_norm,
            "brow_furrow": self.brow_furrow,
            "forward_lean": self.forward_lean,
            "body_stability": self.body_stability,
            "hand_speed": self.hand_speed,
            "focus_score": self.focus_score,
            "cognitive_load": self.cognitive_load,
            "fatigue_score": self.fatigue_score,
            "procrastin_score": self.procrastin_score,
        }


# ── Model output ──────────────────────────────────────────────────────────────

@dataclass
class ModelPrediction:
    switch_probability:      float = 0.0
    procrastination_score:   float = 0.0
    cognitive_state:         str   = "unknown"
    cognitive_state_probs:   Dict[str, float] = field(default_factory=dict)
    switch_confidence:       float = 0.0   # 0=uncertain, 1=very confident
    state_confidence:        float = 0.0   # 0=uncertain, 1=very confident
    timestamp:               float = 0.0
    model_version:           str   = "lstm-v1-numpy"

    @property
    def label(self) -> str:
        sp = self.switch_probability
        if sp > 0.75: return "Switch Imminent"
        if sp > 0.50: return "Switch Likely"
        if sp > 0.25: return "Switch Possible"
        return "Stable"


# ── Main model ────────────────────────────────────────────────────────────────

class CognitiveLSTMModel:
    """
    LSTM-based real-time cognitive state predictor.

    Call predict(features) every frame. Internally maintains a rolling
    30-frame buffer and runs the full LSTM forward pass each time.

    To use pre-trained weights:
        model.load_weights("data/lstm_weights.json")

    To save weights after any future training:
        model.save_weights("data/lstm_weights.json")
    """

    def __init__(
        self,
        sequence_len: int = SEQUENCE_LEN,
        hidden_size:  int = HIDDEN_SIZE,
        weights_path: Optional[str] = None,
    ):
        self.sequence_len = sequence_len
        self.hidden_size  = hidden_size
        self.lstm = NumpyLSTMCell(FEATURE_DIM, hidden_size)
        self.head = NumpyLSTMHead(hidden_size, NUM_COG_STATES)

        self._buffer: deque = deque(maxlen=sequence_len)
        self._pred_history: deque = deque(maxlen=300)
        self._n_predictions = 0

        if weights_path and os.path.exists(weights_path):
            self.load_weights(weights_path)
            logger.info(f"CognitiveLSTMModel: loaded weights from {weights_path}")
        else:
            logger.info(
                "CognitiveLSTMModel: Xavier-random init (untrained). "
                "Collect session data via FeatureLogger to train."
            )

    def predict(self, features: ModelFeatureVector) -> ModelPrediction:
        """Feed one feature vector; return prediction (O(seq_len × hidden²))."""
        self._buffer.append(features.to_array())

        h = np.zeros(self.hidden_size, dtype=np.float32)
        c = np.zeros(self.hidden_size, dtype=np.float32)
        for vec in self._buffer:
            h, c = self.lstm.forward(vec, h, c)

        switch_prob, proc_score, cog_probs = self.head.forward(h)

        # Confidence metrics
        switch_conf = float(abs(switch_prob - 0.5) * 2.0)
        entropy     = float(-np.sum(cog_probs * np.log(cog_probs + 1e-8)))
        state_conf  = float(max(0.0, 1.0 - entropy / np.log(NUM_COG_STATES + 1e-8)))

        best_idx   = int(np.argmax(cog_probs))
        cog_state  = IDX_COG_STATE.get(best_idx, "unknown")
        cog_dict   = {IDX_COG_STATE[i]: round(float(p), 4) for i, p in enumerate(cog_probs)}

        pred = ModelPrediction(
            switch_probability    = round(switch_prob, 4),
            procrastination_score = round(proc_score, 4),
            cognitive_state       = cog_state,
            cognitive_state_probs = cog_dict,
            switch_confidence     = round(switch_conf, 3),
            state_confidence      = round(state_conf, 3),
            timestamp             = time.time(),
        )
        self._pred_history.append(pred)
        self._n_predictions += 1
        return pred

    # ── Weight I/O ────────────────────────────────────────────────────────────

    def save_weights(self, path: str):
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        payload = {
            "lstm": {k: getattr(self.lstm, k).tolist()
                     for k in ("Wf","bf","Wi","bi","Wg","bg","Wo","bo")},
            "head": {"W": self.head.W.tolist(), "b": self.head.b.tolist()},
            "meta": {
                "feature_dim":  FEATURE_DIM, "hidden_size": self.hidden_size,
                "sequence_len": self.sequence_len, "saved_at": time.time(),
                "n_predictions": self._n_predictions,
            },
        }
        with open(path, "w") as f:
            json.dump(payload, f)
        logger.info(f"Weights saved → {path}")

    def load_weights(self, path: str):
        with open(path) as f:
            w = json.load(f)
        self.lstm.load_weights(w.get("lstm", {}))
        self.head.load_weights(w.get("head", {}))

    # ── Stats ─────────────────────────────────────────────────────────────────

    def get_model_stats(self) -> dict:
        if not self._pred_history:
            return {"n_predictions": 0, "buffer_fill": len(self._buffer),
                    "sequence_len": self.sequence_len}
        probs = [p.switch_probability for p in self._pred_history]
        return {
            "n_predictions":          self._n_predictions,
            "avg_switch_probability": round(float(np.mean(probs)), 3),
            "avg_switch_confidence":  round(float(np.mean(
                [p.switch_confidence for p in self._pred_history])), 3),
            "avg_state_confidence":   round(float(np.mean(
                [p.state_confidence  for p in self._pred_history])), 3),
            "buffer_fill":   len(self._buffer),
            "sequence_len":  self.sequence_len,
            "hidden_size":   self.hidden_size,
            "model_version": "lstm-v1-numpy",
        }


# ── Feature builder (existing pipeline → model) ───────────────────────────────

def build_feature_vector(signals, cognitive, proc_score: float) -> ModelFeatureVector:
    """
    Convert ProcessedSignals + CognitiveSnapshot → ModelFeatureVector.
    Called each frame in main.py after Stage 3 (cognitive modules).
    """
    def _g(obj, attr, default=0.0):
        return float(getattr(obj, attr, default))

    return ModelFeatureVector(
        head_yaw_dev     = min(_g(signals, "head_yaw_dev")      / 30.0, 1.0),
        gaze_instability = min(_g(signals, "gaze_instability")  / 0.5,  1.0),
        ear_normalised   = min(_g(signals, "ear",   0.28)       / 0.4,  1.0),
        blink_rate_norm  = min(_g(signals, "blink_rate", 15)    / 30.0, 1.0),
        brow_furrow      = min(_g(signals, "brow_furrow"),               1.0),
        forward_lean     = min(_g(signals, "forward_lean"),              1.0),
        body_stability   = min(_g(signals, "body_stability", 1.0),       1.0),
        hand_speed       = min(_g(signals, "hand_speed")        / 0.3,  1.0),
        focus_score      = _g(cognitive, "focus_score",    0.5),
        cognitive_load   = _g(cognitive, "cognitive_load", 0.3),
        fatigue_score    = _g(cognitive, "fatigue_score",  0.0),
        procrastin_score = float(proc_score),
    )
